name: jaeger-tutorial
services:
  jaeger-tutorial:
    public: true
    image: vertigo/jaeger-tutorial
    build: .
    environment:
      - SERVER_PORT=9000
      - JAEGER_AGENT_HOST=jaeger-agent
      - JAEGER_AGENT_PORT=6831
    ports:
      - 9000
    resources:
      cpu: 400m
      memory: 512Mi

  # jaeger-query:
  #   public: true
  #   image: jaegertracing/jaeger-query
  #   environment:
  #     - CASSANDRA_SERVERS=cassandra
  #     - CASSANDRA_KEYSPACE=jaeger_v1_dc1
  #     #- JAEGER_AGENT_PORT=tcp://jaeger-agent:5775
  #   ports:
  #     - 16686
  #   resources:
  #     cpu: 200m
  #     memory: "256Mi"
  # jaeger-collector:
  #   public: false
  #   image: jaegertracing/jaeger-collector
  #   environment:
  #     - CASSANDRA_SERVERS=cassandra
  #     - CASSANDRA_KEYSPACE=jaeger_v1_dc1
  #     - COLLECTOR_ZIPKIN_HTTP_PORT=9411 
  #   #command: ["--cassandra.keyspace=jaeger_v1_dc1", "--cassandra.servers=cassandra", "--collector.zipkin.http-port=9411"]
  #   ports:
  #     - 14269
  #     - 14268
  #     - 14250
  #     - 9411
  #   resources:
  #     cpu: 200m
  #     memory: "256Mi"
  # #
  # # JAEGER AGENT
  # #
  # jaeger-agent:
  #   public: false
  #   image: jaegertracing/jaeger-agent
  #   environment:
  #     - REPORTER_GRPC_HOST_PORT=jaeger-collector:14250
  #   ports:
  #     - 5775
  #     - 6831
  #     - 6832
  #     - 5778
  #   resources:
  #     cpu: 200m
  #     memory: "256Mi"
  # #
  # # CASSANDRA
  # #
  # cassandra:
  #   public: false
  #   image: cassandra:3
  #   ports:
  #     - 9042
  #   environment:
  #     - MAX_HEAP_SIZE=1024M
  #     - HEAP_NEWSIZE=256M
  #     - CLUSTER_SIZE=1
  #   resources:
  #     cpu: 1.0
  #     memory: "2048Mi"
  #     storage: 1Gi
  #   volumes:
  #     - /var/lib/cassandra
  # cassandra-schema:
  #   public: false
  #   image: jaegertracing/jaeger-cassandra-schema
  #   resources:
  #     cpu: 100m
  #     memory: "128Mi"
